### ISSUE TITLE
Error when starting 'weatherUi.py'

### ISSUE THREAD

**Issue by ghost** [Crilum/pyqt5-weather-app#1]
When I am trying to start `weatherUi.py`, I always get this error:
```
Traceback (most recent call last):
  File "my path\weatherUi.py", line 440, in <module>
    main()
  File "my path\weatherUi.py", line 430, in main
    window = weatherGui()
  File "my path\weatherUi.py", line 133, in __init__
    out("info@weatherGui", "loading ui file...")
  File "my path\weatherUi.py", line 118, in out
    if not prefs.output == "None":
AttributeError: type object 'prefs' has no attribute 'output'
```
Please, fix your code

**Comment by Crilum** [comment]
Oh.. Sorry. I believe that I forgot to catch the error if there's no `$HOME/.config/weatherGui/preferences.txt` file (Yes, it's not going to work on Windows, sorry. I developed this for Linux). My bad.
It should start now.
But, the app still won't work (you won't be able to get the weather, but the main functionality of the app works) because the API I was using isn't online anymore (It was using the free Heroku plan, and since they shut down the free plan it hasn't worked.). I've been thinking about finding another free API, but I just haven't really gotten to it, as this is mostly a demo project, a test to see how PyQt5 works.

Wishing you a good day!

**Comment by Crilum** [comment]
@Mark2051 I've fixed this app, if you're still interested in trying it (it still won't work on Windows though; I've yet to add the config compatibility for Windows, and the app doesn't work without it).

It uses OpenWeatherMap for weather data now, so you'll need a free API key if you do end up trying it.
